package timaxa007.fabrication;

import com.google.common.collect.Lists;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.ItemBlock;
import net.minecraft.network.NetworkManager;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.network.NetworkRegistry;
import net.minecraftforge.fml.common.registry.ForgeRegistries;
import net.minecraftforge.fml.common.registry.GameRegistry;

@Mod(modid = FabricationMod.MODID, name = FabricationMod.NAME, version = FabricationMod.VERSION, useMetadata = true)
public class FabricationMod {

	public static final String
	MODID = "fabrication",
	NAME = "Fabrication Mod",
	VERSION = "0.1";

	@Mod.Instance(MODID)
	public static FabricationMod instance;
	
	@Mod.Metadata(MODID)
	public static ModMetadata metadata;

	public static Block fabrication;

	@Mod.EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		metadata = metadata(event.getModMetadata());
		fabrication = new BlockFabrication(Material.IRON).
				setRegistryName(MODID, "fabrication").
				setUnlocalizedName("fabrication").
				setCreativeTab(CreativeTabs.MISC);
		ForgeRegistries.BLOCKS.register(fabrication);
		ForgeRegistries.ITEMS.register(new ItemBlock(fabrication).setRegistryName(fabrication.getRegistryName()));
		GameRegistry.registerTileEntity(TileEntityFabrication.class, "fabrication");

		NetworkRegistry.INSTANCE.registerGuiHandler(instance, new GuiHandler());
	}

	private ModMetadata metadata(ModMetadata modMetadata) {
		modMetadata.authorList = Lists.newArrayList("timaxa007");
		modMetadata.modId = MODID;
		modMetadata.name = NAME;
		modMetadata.version = VERSION;
		modMetadata.autogenerated = false;
		return modMetadata;
	}

}
